### ISSUE TITLE
Mercurial - Delete branches that are closed

### ISSUE THREAD

**Issue by chris5287** [gvalkov/jenkins-autojobs#34]
For mercurial, it is more likely for a branch to be closed than deleted. Is it possible to get it to delete a job if the branch is closed instead?

**Comment by gvalkov** [comment]
Yes, that makes sense. It's currently not possible, but I'll look into adding it. Thanks for the suggestion.

**Comment by chris5287** [comment]
For local filesystem repos, just removing the '-C' from the hg branches command fixes this.

Not sure how to modify remote repos as the code is using hg apis and I cannot find any documentation for the api's anywhere.

**Comment by gvalkov** [comment]
Yes, it is straightforward for local repositories, but apparently impossible/very hard for remote ones. I did some digging through the mercurial api and coudn't find any definite answer. The `wirepeer.getbundle` method looks promising. I hope to work on this during the weekend.
