### ISSUE TITLE
Repo substitution

### ISSUE THREAD

**Issue by jeroen-s** [gvalkov/jenkins-autojobs#35]
It would be useful to have {repo} available as a substitution to enable the use of template jobs 'across' repositories.

**Comment by gvalkov** [comment]
Hello and sorry for the late reply. As of commit f199b5f6d503281601e6a9676a5dd262f8ab1d96 and version 0.15.1, the `repo` and `repo-orig` placeholders are available to the `namefmt` and `substitute` options. 

Please close the issue if this functionality satisfies your use case. Thanks!
