### ISSUE TITLE
Do not create jobs for closed branches in mercurial

### ISSUE THREAD

**Issue by qatesterforever** [gvalkov/jenkins-autojobs#48]
Hi,
I am running jenkins-makejobs-hg using the basic instructions, but it seems to be creating new jobs for branches that are already closed. I am also running multiple instances of jenkins-makejobs-hg so I am setting cleanup : false.  Is there a way to configure it such that it only creates jobs for mercurial branches that are not closed?

Thank you so much!

**Comment by gvalkov** [comment]
Hello @qatesterforever,

I'm afraid this is the only available behaviour at the moment. Listing only open branches is easy to do with a local repository, but I haven't found a way to do it with remote mercurial repositories. As soon as I figure it out, I'll add something like a `list-closed: true` to the config file.

In the meantime, you can just remove the `-c` flag from `hg.py/hg_branch_iter_local()` if you're using a local repository.

Kind regards,
Georgi

**Comment by qatesterforever** [comment]
Ok great thank you for your quick response.  I'll try your recommendation with a local repo as soon as I can and post my findings.

**Comment by gvalkov** [comment]
No problem. I added the `list-closed` option in 0f92ba46cf0c3505e550903a6f2919cbea231d4a, with a warning that it works only for local repositories.

**Comment by qatesterforever** [comment]
I upgraded and set the list-closed=false and it is still processing closed branches.
These are my settings:
repo: file:///var/lib/jenkins/<my_repo>

#-----------------------------------------------------------------------------
# Process closed branches. Note that this works only for local repositories at
# the moment. Defaults to 'true'.
list-closed: false

**Comment by qatesterforever** [comment]
Actually I take my last comment back.  I was using the wrong repo setting format.  Once I set my repo setting like this "repo: /var/lib/jenkins/<my_repo>" the list-closed option was respected.  

Thank you for the fix!

**Comment by gvalkov** [comment]
I'm glad it works.
