### ISSUE TITLE
Latest features not visible

### ISSUE THREAD

**Issue by marta-lapina** [gvalkov/jenkins-autojobs#50]
Hello, I tried using the release 0.17.0 with Jenkins 1.609 and I can't see this feature working:

"Jenkins-autojobs will now use the job description field to store its metadata. Expect to see (created by jenkins-autojobs) and (jenkins-autojobs-tag: $tagname [...]) lines appended to the description of all managed jobs."
See https://github.com/gvalkov/jenkins-autojobs/issues/28

There is nothing in the job description field, and the XML element <createdByJenkinsAutojobs> still gets created. Autojobs sets a tag value for jobs and stores in this element. 

< createdByJenkinsAutojobs >< ref >refs/heads/feature/test-2</ ref >< tag >test< /tag >< /createdByJenkinsAutojobs >< /project >

From my YAML config file:    "tag: test"

Why don't I see the new feature working? Is there something that I need to add/remove from the YAML file?

**Comment by gvalkov** [comment]
Hello @marta-lapina,

Doh! I forgot to change the default behavior. Sorry for that - you can either set `tag-method: description` in your config or upgrade to 0.17.2. 

Fixed in 8471d897206f9ded7f56eb83fcc99cde7a58deac

**Comment by marta-lapina** [comment]
Thank you!
