### ISSUE TITLE
Honor trusted Certificate Authorities (/etc/ssl/certs) for https 

### ISSUE THREAD

**Issue by PaulKlumpp** [gvalkov/jenkins-autojobs#55]
More a question than an issue:
How do I get Jenkins-Autojobs to honor the locally installed CA-certificates?

The background: 
We let Jenkins-Autojobs connect to our Jenkins, which is situated behind a Apache. Apache is reachable by https. It has a server certificate issued by the corporate Certificate Authority. The CA-certs are installed locally in /etc/ssl/certs ... and I thought Python and its http-libs would honor those. Of course, it depends on the lib.

In the end, Python threw an SSL-error. It could not check the server certificate, said it is untrusted and exited.

**Comment by gvalkov** [comment]
Hello @PaulKlumpp. I just had a jab at fixing this in 8947a7979cbf738756912d8e74137e2f24cc2519 - you should be able to disable ssl verification with the `--no-verify-ssl` command-line switch. There is also a '--cert-bundle' that should let you specify an alternative certificate bundle or directory.

These options just expose the [`verify` and `cert`](http://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification) args of `requests.post()` (which is what jenkins-webapi uses internally).

I would appreciate it if you let me know if this solves the problem for you. You can install the tip version with:

```
pip install -U git+git://github.com/gvalkov/jenkins-autojobs.git@8947a7979cbf738756912d8e74137e2f24cc2519
```

Thanks,
G.

**Comment by PaulKlumpp** [comment]
I'll let you know. 
I have just been looking over the changes. Options look good so far!

**Comment by PaulKlumpp** [comment]
I am using the cert-bundle option. It works like a charm. Thanks.
